### ISSUE TITLE
Cant start termux-x11 session

### ISSUE THREAD

**Issue by catgirlcataclysm** [RobertSzujo/Termux-UbuntuBox#1]
upon running start-x11-server.sh, this is what I get as an error.
I've tried a fresh install of termux and termux-x11
I'm running grapheneos Incase that could cause any issues 

```
ubuntu@localhost:~$ ~/start-x11-server.sh
Started XFCE4 server. GUI should be visible in Termux-X11 app. Use Quit on the Termux-X11 notification to stop XFCE4 session.
/usr/bin/startxfce4: X server already running on display :0
xrdb: Connection refused
xrdb: Can't open display ':0'
xfce4-session: Cannot open display: .
Type 'xfce4-session --help' for usage.
```

**Comment by Giova445** [comment]
Trabajo going to the .zip of termux-11 on termux and type dpkg-i termux-x11.deb

**Comment by catgirlcataclysm** [comment]
> Trabajo going to the .zip of termux-11 on termux and type dpkg-i termux-x11.deb

I tried that and I had termux-x11 running, the issue persists.

**Comment by Giova445** [comment]
which version of termux x11 are you using? for some reason I tried using the latests releases and it seems is not working

**Comment by catgirlcataclysm** [comment]
> which version of termux x11 are you using? for some reason I tried using the latests releases and it seems is not working

I'm using latest, do you know what the newest working version is?

**Comment by Giova445** [comment]
it is complicated to tell you, because for some reason the latest build works well with only proot distro clean install, not this one, so I have a folder with an older version of termux x11 and with this one is working here :), let my try to get a shareable link for you

**Comment by Giova445** [comment]
looking into the documentation of termux x11 it seems they use  `export DISPLAY=:1` try changing it with nano ˜/start-11-server.sh

**Comment by Giova445** [comment]
https://github.com/SaicharanKandukuri/T-X11/actions/runs/2510011847
please download the artifact here, this is the version is working for me

**Comment by catgirlcataclysm** [comment]
> https://github.com/SaicharanKandukuri/T-X11/actions/runs/2510011847
> please download the artifact here, this is the version is working for me

thank you, but that build artifact is expired, otherwise I would lol
thank you for continuing to help me with this though

**Comment by Giova445** [comment]
HAHAH lol, i did not notice, try with this one instead, 
https://drive.google.com/file/d/154U_SVtOQ1aVG3h3QbIlLfvCcUpKF7Rx/view?usp=drivesdk

**Comment by catgirlcataclysm** [comment]
this is closer than I've been before, startubuntubox-termux-x11 actually opens the app now

still the same error though, and I tried with both DISPLAY=:0 and DISPLAY=:1

**Comment by Giova445** [comment]
it seems that the error is regarding with wayland, could you please try with the first steps and try again ? `Example: If you placed the .tar.xz file on the root folder of your shared storage, the command would be "termux-restore ./storage/shared/termux-ubuntubox-20230130.tar.xz"

If done, restart Termux (this is important, as you can't access the new commands before restart). close termux from notification panel`

**Comment by catgirlcataclysm** [comment]
> it seems that the error is regarding with wayland, could you please try with the first steps and try again ? `Example: If you placed the .tar.xz file on the root folder of your shared storage, the command would be "termux-restore ./storage/shared/termux-ubuntubox-20230130.tar.xz"
> 
> If done, restart Termux (this is important, as you can't access the new commands before restart). close termux from notification panel`

I seem to still have the exact same issue
no screens are found

**Comment by Giova445** [comment]
I recently got the same issue, and the way I fixed this, it's going to termux x11 info app, then going to storage, and clear cache

**Comment by catgirlcataclysm** [comment]
OH MY GOODNESS IT WORKS
thank you so much!!!!
